org: itechdom
app: markab-io 
service: markab

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

custom:
  client:
    bucketName: markab-io-frontend
    distributionFolder: build 

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - DomainName: ${self:custom.client.bucketName}.s3.amazonaws.com
              Id: S3-${self:custom.client.bucketName}
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            TargetOriginId: S3-${self:custom.client.bucketName}
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
          # Remove the Aliases property to avoid domain linking
          # Aliases:
          #   - markab.io
          #   - www.markab.io
          DefaultRootObject: index.html
          PriceClass: PriceClass_100
          Restrictions:
            GeoRestriction:
              RestrictionType: none

  Outputs:
    CloudFrontDistributionId:
      Value: !Ref CloudFrontDistribution
      Export:
        Name: CloudFrontDistributionId
    CloudFrontDistributionDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: CloudFrontDistributionDomainName
