org: itechdom
app: markab 
service: markab  # This names your service
provider:
  name: aws
  runtime: nodejs20.x  # Assuming you're using Node.js 14.x
  region: us-east-1
custom:
  client:
    bucketName: markab-io-frontend
    distributionFolder: build 

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin