service: markab  # This names your service

provider:
  name: aws
  runtime: nodejs20.x  # Assuming you're using Node.js 20.x
  region: us-east-1

custom:
  client:
    bucketName: markab-io-frontend
    distributionFolder: build

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin
  - serverless-dotenv-plugin

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - DomainName: !Sub '${custom.client.bucketName}.s3.amazonaws.com'
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 0
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
            MinimumProtocolVersion: TLSv1.2_2021
          DefaultRootObject: index.html

  Outputs:
    CloudFrontDistributionId:
      Value:
        Ref: CloudFrontDistribution
      Export:
        Name: CloudFrontDistributionId
    CloudFrontDistributionDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: CloudFrontDistributionDomainName
